version: "3"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-mecross
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: mcp
      TZ: Asia/Seoul
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
  redis:
    image: redis:6.2.6-alpine
    container_name: redis-mecross
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    restart: always
    command: redis-server /usr/local/conf/redis.conf